version: '3'
services:
  content-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: dockerhub.io/mosaic:latest
    environment:
      - BUILD_ENV=dev

    ports:
      - 5000:5000
    # command: /bin/bash -c "sleep 7 && python3 app.py"

