channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - make
  - pip
  - python=3.7
  - pip:
    - --index-url=https://pypi.org/simple
    - --trusted-host=[pypi.org]
    - -rrequirements.txt
    