# Default values for audio-processing-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

docker:
  # Default hub for docker images.
  # Releases are published to docker hub under mentioned 'user' project.
  # Daily builds from prow are on gcr.io
  registry: dockerhub.io
  # User for the docker hub
  user: 
  # User for the docker hub
  password: 
  # Image name
  image: mosaic
  # Default tag for images.
  tag: latest
  # Default image pull policy.
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  httpPort: 80

app:
  # Default log level [error, warn, info, debug]
  logLevel: info
  httpPort: 5000
  tmpfsLocation: /tmp/app-server
  maxWorker: 10

  objectStore:
    type: 1
    accountName: ""
    accountKey: ""
    endpointSuffix: ""
    containerName: ""
    prefix: ''

prometheus:
  enabled: false
  port: 8081
  path: "/metrics"

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

deploymentStrategy:
  replicaCount: 1
  startegy: RollingUpdate
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
  terminationGracePeriodSeconds: 20
  autoScaler:
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
